name = "aoc2024"
version = "1.0.0"

target = "erlang"
gleam = ">= 1.6.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_community_maths = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
